
project_id = "rsmvjsokqolxgczclqjv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "https://finanzacreativa.live"
additional_redirect_urls = ["https://finanzacreativa.live", "http://127.0.0.1:3000", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
# Aggiunta esplicita per disabilitare la conferma email
enable_email_confirmations = false
email_confirm_required = false
email_autoconfirm = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[[auth.external.google]]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "https://rsmvjsokqolxgczclqjv.supabase.co/auth/v1/callback"

[edge_runtime]
enabled = true
port = 54327

[[edge_runtime.function]]
name = "send-notifications"
source = "./supabase/functions/send-notifications"
verify_jwt = true

[[edge_runtime.function]]
name = "setup-cron"
source = "./supabase/functions/setup-cron"
verify_jwt = true

[[edge_runtime.function]]
name = "test-whatsapp"
source = "./supabase/functions/test-whatsapp"
verify_jwt = true

[[edge_runtime.function]]
name = "check-auth-config"
source = "./supabase/functions/check-auth-config"
verify_jwt = true
